# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 1.14.x
# License is REQUIRED after 1.16
license='GNU GPLv3'

[[mods]]
modId="ae2additions"
version="0.0.0.0.1"
displayName="AE Additions"
credits="The AEAdditions dev team"
authors="MasterYodA"
description='''
A mod with helpful additions for Applied Energistics 2

Special credit for original mod authors M3gaFr3ak/DrummerMC and Textures by PaleoCrafter and Cyntain
'''
[[dependencies.ae2additions]]
modId="forge"
mandatory=true
versionRange="[40.0.0,41.0.0)"
ordering="NONE"
side="BOTH"
[[dependencies.ae2additions]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"
[[dependencies.ae2additions]]
modId="ae2"
mandatory=true
versionRange="[11.6.1-beta,)"
ordering="AFTER"
side="BOTH"
[[dependencies.ae2additions]]
modId="mekanism"
mandatory=false
ordering="AFTER"
versionRange="[10.0.20.447,)"
side="BOTH"
[[dependencies.ae2additions]]
modId="appmek"
mandatory=false
ordering="AFTER"
versionRange="[1.1.1,)"
side="BOTH"
[[dependencies.ae2additions]]
modId="ae2things"
mandatory=false
ordering="AFTER"
versionRange="[1.0.0,)"
side="BOTH"
[[dependencies.ae2additions]]
modId="megacells"
mandatory=false
ordering="AFTER"
versionRange="[1.4.0,)"
side="BOTH"
[[dependencies.ae2additions]]
modId="ftbteams"
mandatory=false
ordering="AFTER"
versionRange="[1802.2.6-build.51,)"
side="BOTH"